clinical_a <- read.csv("C:/Users/cheny/Desktop/cox_rg/data/clinical_A.csv")
expr_a <- read.csv("C:/Users/cheny/Desktop/cox_rg/data/expr_A.csv")
data = c(clinical_a, expr_a)

gender <- as.factor(data$Gender)
diag <- as.factor(data$Diag)
diff <- as.factor(data$differientiation)
stage <- as.factor(data$stage)
days <- data$Days
status <- data$Status

cox.mod <- coxph(Surv(days, status) ~ gender + diag + diff + stage)

Tumor_CD45 <- data$Tumor_CD45
Tumor_CD3 <- data$Tumor_CD3
Tumor_Rb_IgG <- data$Tumor_Rb_IgG
Tumor_PD_L1 <- data$Tumor_PD_L1
Tumor_CD56 <- data$Tumor_CD56
Tumor_S6 <- data$Tumor_S6
Tumor_CD4 <- data$Tumor_CD4
Tumor_PD_1 <- data$Tumor_PD_1
Tumor_HLA_DR <- data$Tumor_HLA_DR
Tumor_Histone_H3 <- data$Tumor_Histone_H3
Tumor_Ki_67 <- data$Tumor_Ki_67
Tumor_CTLA4 <- data$Tumor_CTLA4
Tumor_CD11c <- data$Tumor_CD11c
Tumor_SMA <- data$Tumor_SMA
Tumor_Ms_IgG2a <- data$Tumor_Ms_IgG2a
Tumor_GZMB <- data$Tumor_GZMB
Tumor_CD68 <- data$Tumor_CD68
Tumor_GAPDH <- data$Tumor_GAPDH
Tumor_CD20 <- data$Tumor_CD20
Tumor_CD8 <- data$Tumor_CD8
Tumor_PanCk <- data$Tumor_PanCk
Tumor_Ms_IgG1 <- data$Tumor_Ms_IgG1
Tumor_Fibronectin <- data$Tumor_Fibronectin
Tumor_Beta_2_microglobulin <- data$Tumor_Beta_2_microglobulin
Tumor_ICOS <- data$Tumor_ICOS
Tumor_CD44 <- data$Tumor_CD44
Tumor_CD40 <- data$Tumor_CD40
Tumor_PD_L2 <- data$Tumor_PD_L2
Tumor_CD25 <- data$Tumor_CD25
Tumor_CD127 <- data$Tumor_CD127
Tumor_CD80 <- data$Tumor_CD80
Tumor_CD27 <- data$Tumor_CD27
Tumor_IDO1 <- data$Tumor_IDO1
Tumor_ARG1 <- data$Tumor_ARG1
Tumor_LAG3 <- data$Tumor_LAG3
Tumor_VISTA <- data$Tumor_VISTA
Tumor_STING <- data$Tumor_STING
Tumor_OX40L <- data$Tumor_OX40L
Tumor_B7_H3 <- data$Tumor_B7_H3
Tumor_GITR <- data$Tumor_GITR
Tumor_4_1BB <- data$Tumor_4_1BB
Tumor_Tim_3 <- data$Tumor_Tim_3
Tumor_PTEN <- data$Tumor_PTEN
Tumor_ER_alpha <- data$Tumor_ER_alpha
Tumor_S100B <- data$Tumor_S100B
Tumor_NY_ESO_1 <- data$Tumor_NY_ESO_1
Tumor_EpCAM <- data$Tumor_EpCAM
Tumor_MART1 <- data$Tumor_MART1
Tumor_PR <- data$Tumor_PR
Tumor_Her2 <- data$Tumor_Her2
Tumor_Bcl_2 <- data$Tumor_Bcl_2
Tumor_CD34 <- data$Tumor_CD34
Tumor_FOXP3 <- data$Tumor_FOXP3
Tumor_CD163 <- data$Tumor_CD163
Tumor_CD45RO <- data$Tumor_CD45RO
Tumor_FAP_alpha <- data$Tumor_FAP_alpha
Tumor_CD66b <- data$Tumor_CD66b
Tumor_CD14 <- data$Tumor_CD14
Stroma_CD45 <- data$Stroma_CD45
Stroma_CD3 <- data$Stroma_CD3
Stroma_Rb_IgG <- data$Stroma_Rb_IgG
Stroma_PD_L1 <- data$Stroma_PD_L1
Stroma_CD56 <- data$Stroma_CD56
Stroma_S6 <- data$Stroma_S6
Stroma_CD4 <- data$Stroma_CD4
Stroma_PD_1 <- data$Stroma_PD_1
Stroma_HLA_DR <- data$Stroma_HLA_DR
Stroma_Histone_H3 <- data$Stroma_Histone_H3
Stroma_Ki_67 <- data$Stroma_Ki_67
Stroma_CTLA4 <- data$Stroma_CTLA4
Stroma_CD11c <- data$Stroma_CD11c
Stroma_SMA <- data$Stroma_SMA
Stroma_Ms_IgG2a <- data$Stroma_Ms_IgG2a
Stroma_GZMB <- data$Stroma_GZMB
Stroma_CD68 <- data$Stroma_CD68
Stroma_GAPDH <- data$Stroma_GAPDH
Stroma_CD20 <- data$Stroma_CD20
Stroma_CD8 <- data$Stroma_CD8
Stroma_PanCk <- data$Stroma_PanCk
Stroma_Ms_IgG1 <- data$Stroma_Ms_IgG1
Stroma_Fibronectin <- data$Stroma_Fibronectin
Stroma_Beta_2_microglobulin <- data$Stroma_Beta_2_microglobulin
Stroma_ICOS <- data$Stroma_ICOS
Stroma_CD44 <- data$Stroma_CD44
Stroma_CD40 <- data$Stroma_CD40
Stroma_PD_L2 <- data$Stroma_PD_L2
Stroma_CD25 <- data$Stroma_CD25
Stroma_CD127 <- data$Stroma_CD127
Stroma_CD80 <- data$Stroma_CD80
Stroma_CD27 <- data$Stroma_CD27
Stroma_IDO1 <- data$Stroma_IDO1
Stroma_ARG1 <- data$Stroma_ARG1
Stroma_LAG3 <- data$Stroma_LAG3
Stroma_VISTA <- data$Stroma_VISTA
Stroma_STING <- data$Stroma_STING
Stroma_OX40L <- data$Stroma_OX40L
Stroma_B7_H3 <- data$Stroma_B7_H3
Stroma_GITR <- data$Stroma_GITR
Stroma_4_1BB <- data$Stroma_4_1BB
Stroma_Tim_3 <- data$Stroma_Tim_3
Stroma_PTEN <- data$Stroma_PTEN
Stroma_ER_alpha <- data$Stroma_ER_alpha
Stroma_S100B <- data$Stroma_S100B
Stroma_NY_ESO_1 <- data$Stroma_NY_ESO_1
Stroma_EpCAM <- data$Stroma_EpCAM
Stroma_MART1 <- data$Stroma_MART1
Stroma_PR <- data$Stroma_PR
Stroma_Her2 <- data$Stroma_Her2
Stroma_Bcl_2 <- data$Stroma_Bcl_2
Stroma_CD34 <- data$Stroma_CD34
Stroma_FOXP3 <- data$Stroma_FOXP3
Stroma_CD163 <- data$Stroma_CD163
Stroma_CD45RO <- data$Stroma_CD45RO
Stroma_FAP_alpha <- data$Stroma_FAP_alpha
Stroma_CD66b <- data$Stroma_CD66b

cox.mod <- coxph(Surv(days, status) ~ Tumor_CD45 + Tumor_CD3 + Tumor_Rb_IgG + Tumor_PD_L1 + Tumor_CD56 + Tumor_S6 + Tumor_CD4 + Tumor_PD_1 + Tumor_HLA_DR + Tumor_Histone_H3 + Tumor_Ki_67 + Tumor_CTLA4 + Tumor_CD11c + Tumor_SMA + Tumor_Ms_IgG2a + Tumor_GZMB + Tumor_CD68 + Tumor_GAPDH + Tumor_CD20 + Tumor_CD8 + Tumor_PanCk + Tumor_Ms_IgG1 + Tumor_Fibronectin + Tumor_Beta_2_microglobulin + Tumor_ICOS + Tumor_CD44 + Tumor_CD40 + Tumor_PD_L2 + Tumor_CD25 + Tumor_CD127 + Tumor_CD80 + Tumor_CD27 + Tumor_IDO1 + Tumor_ARG1 + Tumor_LAG3 + Tumor_VISTA + Tumor_STING + Tumor_OX40L + Tumor_B7_H3 + Tumor_GITR + Tumor_4_1BB + Tumor_Tim_3 + Tumor_PTEN + Tumor_ER_alpha + Tumor_S100B + Tumor_NY_ESO_1 + Tumor_EpCAM + Tumor_MART1 + Tumor_PR + Tumor_Her2 + Tumor_Bcl_2 + Tumor_CD34 + Tumor_FOXP3 + Tumor_CD163 + Tumor_CD45RO + Tumor_FAP_alpha + Tumor_CD66b + Tumor_CD14 + Stroma_CD45 + Stroma_CD3 + Stroma_Rb_IgG + Stroma_PD_L1 + Stroma_CD56 + Stroma_S6 + Stroma_CD4 + Stroma_PD_1 + Stroma_HLA_DR + Stroma_Histone_H3 + Stroma_Ki_67 + Stroma_CTLA4 + Stroma_CD11c + Stroma_SMA + Stroma_Ms_IgG2a + Stroma_GZMB + Stroma_CD68 + Stroma_GAPDH + Stroma_CD20 + Stroma_CD8 + Stroma_PanCk + Stroma_Ms_IgG1 + Stroma_Fibronectin + Stroma_Beta_2_microglobulin + Stroma_ICOS + Stroma_CD44 + Stroma_CD40 + Stroma_PD_L2 + Stroma_CD25 + Stroma_CD127 + Stroma_CD80 + Stroma_CD27 + Stroma_IDO1 + Stroma_ARG1 + Stroma_LAG3 + Stroma_VISTA + Stroma_STING + Stroma_OX40L + Stroma_B7_H3 + Stroma_GITR + Stroma_4_1BB + Stroma_Tim_3 + Stroma_PTEN + Stroma_ER_alpha + Stroma_S100B + Stroma_NY_ESO_1 + Stroma_EpCAM + Stroma_MART1 + Stroma_PR + Stroma_Her2 + Stroma_Bcl_2 + Stroma_CD34 + Stroma_FOXP3 + Stroma_CD163 + Stroma_CD45RO + Stroma_FAP_alpha + Stroma_CD66b)

